class HomeLocators:
    welcome_to_popup = '//*[@id="root"]/div/div[4]/div'
    popup_restaurant_option = '//*[@id="root"]/div/div[4]/div/div/div/div[3]/div[2]'
    popup_save_btn = '//*[@id="root"]/div/div[4]/div/div/div/button'
    sales_btn = '//*[@id="root"]/div/div[2]/div[2]/div/div/div[1]/div/div/div[2]/a[1]'
    drinks_btn = '//*[@id="root"]/div/div[2]/div[2]/div/div/div[1]/div/div/div[2]/a[3]'
    search_bar_text_field = '//*[@id="root"]/div/div[2]/header/div/div/div/span/input'
    zero_results_error_search = '//*[@id="root"]/div/div[2]/header/div/div/div/div[1]'
    change_language_us_btn = '//*[@id="root"]/div/div[1]'
    login_btn = '//*[@id="root"]/div/div[2]/header/div/div/a[1]/span[1]'
    top_logo_btn = '//*[@id="root"]/div/div[2]/header/div/div/a[2]/div/a/img'
    promotional_banner_first_image = '//*[@id="root"]/div/div[2]/div[1]/div/div/div/div/div/div[1]/div[1]/div/div/div/ul/li[9]/a/img'
    promotional_banner_second_image = '//*[@id="root"]/div/div[2]/div[1]/div/div/div/div/div/div[1]/div[1]/div/div/div/ul/li[5]/a/img'
    banner = '//*[@id="root"]/div/div[2]/div[1]/div/div/div/div/div/div[1]/div[1]/div/div/div/ul/li[8]/a'
    external_product_title = '//*[@id="root"]/div/div[2]/div[1]/div/div/div/div/div/div[3]/a[4]/div/div[2]/div[2]/div[1]'